name: Copybara

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

concurrency:
  group: copybara-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  SOT_REPO: Elium/service-platform
  DESTINATION_REPO: mondosha1/mondosha1

jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: setup-copybara-config
        run: |
          echo 'COPYBARA_CONFIG<<EOF' >> $GITHUB_ENV
          cat ./.github/workflows/copybara/copybara.config.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: olivr/copybara-action@v1.2.3
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          access_token: ${{ secrets.COPYBARA_ACCESS_TOKEN }}
          sot_repo: Elium/service-platform
          sot_branch: master
          destination_repo: mondosha1/mondosha1
          destination_branch: master
          push_include: ${{ fromJson(env.COPYBARA_CONFIG).pushInclude }}
          push_replace: ${{ fromJson(env.COPYBARA_CONFIG).pushReplace }}
          push_move: ${{ fromJson(env.COPYBARA_CONFIG).pushMove }}
